/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.PersonsDirectory;
import model.UsersDirectory;

/**
 *
 * @author ASUS
 */
public class AdminViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminViewJPanel
     */
    
    private JPanel MainPanel;
    private UsersDirectory userDirectory;
    private PersonsDirectory personDirectory;
    private Map<String, ArrayList<String>> credentialsHistory;
    
    public AdminViewJPanel(JPanel MainPanel,UsersDirectory userDirectory,PersonsDirectory personDirectory,Map<String, ArrayList<String>> credentialsHistory) {
        initComponents();
        this.MainPanel = MainPanel;
        this.userDirectory = userDirectory;
        this.personDirectory = personDirectory;
        this.credentialsHistory = credentialsHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnCreatePerson = new javax.swing.JButton();
        btnCreateUser = new javax.swing.JButton();
        btnListPerson = new javax.swing.JButton();
        btnListUser = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(167, 199, 231));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText(" Welcome back, Admin");

        btnLogout.setBackground(new java.awt.Color(102, 102, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnCreatePerson.setBackground(new java.awt.Color(102, 102, 255));
        btnCreatePerson.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreatePerson.setText("Create New Person");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnCreateUser.setBackground(new java.awt.Color(102, 102, 255));
        btnCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateUser.setText("Create New User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        btnListPerson.setBackground(new java.awt.Color(102, 102, 255));
        btnListPerson.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListPerson.setText("List All Persons");
        btnListPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPersonActionPerformed(evt);
            }
        });

        btnListUser.setBackground(new java.awt.Color(102, 102, 255));
        btnListUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListUser.setText("List All Users");
        btnListUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListUserActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(102, 102, 255));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setText("Search by NUID");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreateUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreatePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreatePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
         AddPersonJPanel panel = new AddPersonJPanel(MainPanel,personDirectory);
         MainPanel.add("AddPersonJPanel",panel);
         CardLayout layout = (CardLayout) MainPanel.getLayout();
         layout.next(MainPanel);      
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
        CreateUserJPanel panel = new CreateUserJPanel(MainPanel,personDirectory,userDirectory,credentialsHistory);
        MainPanel.add("CreateUserJPanel",panel);
        CardLayout layout = (CardLayout) MainPanel.getLayout();
        layout.next(MainPanel);      
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnListPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPersonActionPerformed
        // TODO add your handling code here:
        PersonListJPanel panel = new PersonListJPanel(MainPanel,personDirectory,userDirectory);
        MainPanel.add("PersonListJPanel",panel);
        CardLayout layout = (CardLayout) MainPanel.getLayout();
        layout.next(MainPanel);  
    }//GEN-LAST:event_btnListPersonActionPerformed

    private void btnListUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListUserActionPerformed
        // TODO add your handling code here:
        UserListJPanel panel = new UserListJPanel(MainPanel,personDirectory,userDirectory,credentialsHistory);
        MainPanel.add("UserListJPanel",panel);
        CardLayout layout = (CardLayout) MainPanel.getLayout();
        layout.next(MainPanel);  
    }//GEN-LAST:event_btnListUserActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchTxt = txtSearch.getText().trim();

        if (searchTxt.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please make sure all search field is filled in before proceeding.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for(Person person : personDirectory.getPersonList()){
            if((person.getNeuID()).equals(searchTxt)){
                if(person.isAccountCreatedStatus()){
                    UserUpdateJPanel panel = new UserUpdateJPanel(MainPanel, personDirectory.searchPerson(searchTxt), personDirectory,userDirectory,credentialsHistory);
                    MainPanel.add("UserUpdateJPanel",panel);
                    CardLayout layout = (CardLayout) MainPanel.getLayout();
                    layout.next(MainPanel);
                    txtSearch.setText("");
                    return;
                }else{
                    DefaultTableModel dtm = new DefaultTableModel();
                    UpdatePersonJPanel panel = new UpdatePersonJPanel(MainPanel, personDirectory.searchPerson(searchTxt),dtm, personDirectory,userDirectory);
                    MainPanel.add("UpdatePersonJPanel",panel);
                    CardLayout layout = (CardLayout) MainPanel.getLayout();
                    layout.next(MainPanel);
                    txtSearch.setText("");
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(this, "No User Found. Verify NUID.", "No User Found", JOptionPane.ERROR_MESSAGE);
        txtSearch.setText("");
        return;
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Would you like to Logout!","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            MainPanel.remove(this);
            CardLayout layout = (CardLayout) MainPanel.getLayout();
            layout.previous(MainPanel);
        }

    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnListPerson;
    private javax.swing.JButton btnListUser;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    
}
