/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.PersonsDirectory;
import model.UsersDirectory;

/**
 *
 * @author ASUS
 */
public class UserViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserJPanel
     */
    
    private JPanel MainPanel;
    private UsersDirectory userDirectory;
    private PersonsDirectory personDirectory;
    private Map<String, ArrayList<String>> credentialsHistory;
    private Person user;
    
    public UserViewJPanel(JPanel MainPanel,UsersDirectory userDirectory,PersonsDirectory personDirectory,Map<String, ArrayList<String>> credentialsHistory, Person user) {
        initComponents();
        this.MainPanel = MainPanel;
        this.userDirectory = userDirectory;
        this.personDirectory = personDirectory;
        this.credentialsHistory = credentialsHistory;
        this.user = user;
        lblWelcome.setText("Welcome back, "+user.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnViewUser = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();

        setBackground(new java.awt.Color(167, 199, 231));

        btnLogout.setBackground(new java.awt.Color(102, 102, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnViewUser.setBackground(new java.awt.Color(102, 102, 255));
        btnViewUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewUser.setText("View User Details");
        btnViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUserActionPerformed(evt);
            }
        });

        btnUpdateUser.setBackground(new java.awt.Color(102, 102, 255));
        btnUpdateUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateUser.setText("Update User Details");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btnViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Would you like to Logout!","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            MainPanel.remove(this);
            CardLayout layout = (CardLayout) MainPanel.getLayout();
            layout.previous(MainPanel);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUserActionPerformed
        // TODO add your handling code here:
        UserViewDetailsJPanel panel = new UserViewDetailsJPanel(MainPanel, user);
        MainPanel.add("UserViewDetailsJPanel",panel);
        CardLayout layout = (CardLayout) MainPanel.getLayout();
        layout.next(MainPanel);
        
    }//GEN-LAST:event_btnViewUserActionPerformed

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        // TODO add your handling code here:
        UserUpdateJPanel panel = new UserUpdateJPanel(MainPanel, user, personDirectory,userDirectory,credentialsHistory);
        MainPanel.add("UserUpdateJPanel",panel);
        CardLayout layout = (CardLayout) MainPanel.getLayout();
        layout.next(MainPanel);
    }//GEN-LAST:event_btnUpdateUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JButton btnViewUser;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
